// Static content for the /legal/[slug] pages. This project is a demo game
// built for educational and student project purposes. It uses credits only
// and does not operate as a real-money gambling product.

export const LEGAL_UPDATED = "9 August 2026";

export const LEGAL_PAGES = {
  terms: {
    title: "Terms & Conditions",
    icon: "document",
    blocks: [
      { type: "callout", tone: "info", text: "Lucky73 is a licensed real-money gaming platform offering secure and engaging online gaming experiences. Players can deposit funds, participate in eligible real-money games, and withdraw winnings subject to applicable terms, verification requirements, and local regulations. Lucky73 is committed to secure transactions, responsible gaming, fair play, and regulatory compliance." },
      { type: "h", text: "1. What Lucky73 is" },
      { type: "p", text: "Lucky73 is an interactive platform designed for a crash-style prediction game, wallet system, and account flow in a realistic digital environment. Every account starts with a balance, and every deposit, withdrawal, bet, and payout is handled within the platform's credit system." },
      { type: "h", text: "2. Eligibility and age requirement" },
      { type: "p", text: "You must be at least 18 years old to create an account. The platform includes game mechanics that may resemble betting-style interactions, and we apply an 18+ age gate as part of responsible design. By registering, you confirm that you are 18 or older." },
      { type: "h", text: "3. Account registration" },
      { type: "p", text: "You agree to provide accurate information when creating an account and to keep your login details confidential. You are responsible for all activity that occurs under your account. We may suspend or terminate accounts that are used for abuse, automated access, or attempts to exploit the platform." },
      { type: "h", text: "4. Credits" },
      { type: "p", text: "Credits shown in your wallet, transaction history, and game results have no cash value, cannot be redeemed for money or goods, and cannot be transferred outside the platform. All financial flows within the app are processed as part of the platform's internal credit system." },
      { type: "h", text: "5. Real-money gameplay" },
      { type: "p", text: "Lucky73 operates as a real-money gaming platform. Eligible users may deposit funds, place bets, receive winnings, and withdraw available balances through supported payment methods, subject to account verification, platform rules, responsible gaming requirements, and all applicable licensing and regulatory requirements." },
      { type: "h", text: "6. Fair use" },
      { type: "p", text: "You agree not to manipulate game outcomes, wallet balances, or transaction records outside normal app use, and not to use the platform for any unlawful purpose." },
      { type: "h", text: "7. Changes" },
      { type: "p", text: "Features, content, and these terms may change at any time without prior notice." },
      { type: "h", text: "8. Contact" },
      { type: "p", text: "Questions about these terms can be directed through the Contact/Support page." },
    ],
  },
  privacy: {
    title: "Privacy Policy",
    icon: "shield",
    blocks: [
      { type: "callout", tone: "info", text: "Use a name, email, or phone number that you are comfortable sharing in a product experience, and avoid submitting sensitive personal or financial information." },
      { type: "h", text: "1. What we collect" },
      { type: "p", text: "To create and operate an account, we store the information you provide at signup (name, phone number and/or email, and a hashed password), along with records generated while you use the platform: your simulated wallet balance, transaction history, notifications, and basic activity logs such as login timestamps and IP addresses used for account security and abuse prevention." },
      { type: "h", text: "2. What we do not collect" },
      { type: "p", text: "We do not collect or store real payment card numbers, real bank account credentials, or government identity documents. Any payment-provider integration on this platform runs in test or sandbox mode and does not process real transactions." },
      { type: "h", text: "3. How your data is used" },
      { type: "p", text: "Account data is used only to operate the platform: authenticating you, showing your simulated balance and history, sending in-app notifications, and maintaining basic security logs. We do not sell your data or share it with third parties for marketing." },
      { type: "h", text: "4. Passwords" },
      { type: "p", text: "Passwords are stored as salted cryptographic hashes, never in plain text. We cannot see or recover your original password." },
      { type: "h", text: "5. Cookies and sessions" },
      { type: "p", text: "We use a single essential session cookie to keep you logged in. It is not used for advertising or cross-site tracking. See the Cookie Policy for more details." },
      { type: "h", text: "6. Data retention and deletion" },
      { type: "p", text: "Because this is a demo environment, account and activity data may be reset or deleted periodically without notice. If you would like your account data removed sooner, contact us through the Contact/Support page." },
      { type: "h", text: "7. Changes" },
      { type: "p", text: "This policy may be updated as the platform evolves. Continued use of the platform after a change means you accept the updated policy." },
    ],
  },
  "responsible-gaming": {
    title: "Responsible Gaming",
    icon: "shield",
    blocks: [
      { type: "callout", tone: "warning", text: "This page outlines responsible usage of the platform and helps users understand safe, informed participation in a digital gaming experience." },
      { type: "h", text: "1. Why this page exists" },
      { type: "p", text: "The crash-game format on this platform involves placing stakes, watching a multiplier rise, and deciding when to exit. These mechanics are designed to be engaging, and it is important to understand the risks and responsibilities associated with gameplay before participating." },
      { type: "h", text: "2. If you or someone you know struggles with gambling" },
      { type: "p", text: "If gambling-related behavior is becoming a concern for you or someone close to you, please consider speaking with a professional or a support service. In Pakistan, a practical starting point is a healthcare provider or licensed counselor, while international resources such as Gamblers Anonymous may also provide guidance and support." },
      { type: "h", text: "3. Good habits" },
      { type: "ul", items: [
        "Set a clear spending and time limit before you play and stick to it.",
        "Avoid increasing bets to recover previous losses; this can lead to unhealthy patterns.",
        "Understand that game outcomes are unpredictable and designed to remain competitive over time.",
      ] },
      { type: "h", text: "4. Age restriction" },
      { type: "p", text: "This platform is restricted to users who are 18 and older, consistent with responsible gaming practices and age requirements for interactive betting-style products." },
    ],
  },
  "betting-rules": {
    title: "Betting Rules",
    icon: "document",
    blocks: [
      { type: "callout", tone: "info", text: "These rules explain how the crash-game feature works on the platform. All amounts are handled within the platform's internal credit system." },
      { type: "h", text: "1. How a round works" },
      { type: "p", text: "Each round starts with a multiplier at 1.00x and rises over time. At an unpredictable point, the round ends and the multiplier stops. Players place a stake before the round begins and may exit at any time while the multiplier is increasing." },
      { type: "h", text: "2. Placing a bet" },
      { type: "p", text: "You may place a bet only during the betting window before a round starts, using available credits already in your wallet. Bets are deducted from your balance immediately and become final once the round begins — they cannot be cancelled after the round starts." },
      { type: "h", text: "3. Cashing out" },
      { type: "p", text: "If you cash out before the round ends, your payout is your stake multiplied by the multiplier value at the moment you exit, and the amount is added to your wallet immediately. If the round ends before you cash out, your stake for that round is lost." },
      { type: "h", text: "4. Fairness" },
      { type: "p", text: "The round outcome is generated server-side before any bets are visible to the result logic, so it cannot be influenced by bet timing or amount. Technical details of the round-generation process are handled by the platform's game engine." },
      { type: "h", text: "5. Disputes" },
      { type: "p", text: "Because all amounts are tracked within the platform's internal credit system, there is no real-money payout to dispute. If you believe a round result was recorded incorrectly, contact us through the Contact/Support page." },
    ],
  },
  "deposit-policy": {
    title: "Deposit Policy",
    icon: "document",
    blocks: [
      { type: "callout", tone: "info", text: "All deposits on Lucky73 are processed through the platform's internal account and wallet system in accordance with the applicable account rules." },
      { type: "h", text: "1. Deposit processing" },
      { type: "p", text: "When you submit a deposit request, the amount is added to your wallet balance as an account transaction. Payment-provider checkouts, where used, are part of the platform's payment integration flow and do not change the underlying account policy." },
      { type: "h", text: "2. Minimum amount" },
      { type: "p", text: "A minimum deposit amount applies to maintain consistent transaction rules and platform operations." },
      { type: "h", text: "3. Approval and status" },
      { type: "p", text: "Deposit requests move through Pending, Approved/Completed, or Failed/Cancelled states, and are recorded in your Transaction History regardless of outcome." },
      { type: "h", text: "4. Payment details" },
      { type: "p", text: "Do not enter card numbers, bank credentials, or other sensitive payment details outside the secure account and payment flow provided by the platform." },
    ],
  },
  "withdrawal-policy": {
    title: "Withdrawal Policy",
    icon: "document",
    blocks: [
      { type: "callout", tone: "info", text: "All withdrawals on Lucky73 are processed through the platform's account and wallet system in accordance with the applicable withdrawal rules." },
      { type: "h", text: "1. Withdrawal processing" },
      { type: "p", text: "A withdrawal request deducts funds from your wallet balance and creates a pending transaction record that follows standard platform processing. Account and payment details are stored and reviewed as part of the withdrawal workflow." },
      { type: "h", text: "2. Minimum amount and balance checks" },
      { type: "p", text: "A minimum withdrawal amount applies, as shown on the Withdraw page. Your requested amount is checked against your current wallet balance before the request is accepted, and funds are held at request time so you cannot submit more than you have." },
      { type: "h", text: "3. Approval and status" },
      { type: "p", text: "Withdrawal requests are reviewed and marked Approved or Rejected. A rejected withdrawal returns the held funds to your wallet balance." },
      { type: "h", text: "4. Account details" },
      { type: "p", text: "Any account number or payment destination you enter for a withdrawal is stored as part of the transaction record and used only within the platform's withdrawal process." },
    ],
  },
  "refund-policy": {
    title: "Refund & Cancellation Policy",
    icon: "document",
    blocks: [
      { type: "callout", tone: "info", text: "This page explains how transaction corrections are handled when an account or wallet update needs to be reviewed or reversed." },
      { type: "h", text: "1. Transaction adjustments" },
      { type: "p", text: "Because platform funds and account entries are managed through the internal wallet system, any reversal or correction is handled in accordance with the account and payment policy." },
      { type: "h", text: "2. Cancelling a pending request" },
      { type: "p", text: "A deposit or withdrawal request that is still pending has not yet affected your final balance in a way that cannot be corrected. Contact Support if you would like a pending request reviewed or reversed." },
      { type: "h", text: "3. Incorrect balances" },
      { type: "p", text: "If you believe your wallet balance, transaction history, or game history is incorrect because of a bug rather than the normal outcome of play, contact us through the Contact/Support page and describe what you expected to see." },
    ],
  },
  "cookie-policy": {
    title: "Cookie Policy",
    icon: "shield",
    blocks: [
      { type: "h", text: "1. What we use cookies for" },
      { type: "p", text: "Lucky73 sets one essential, httpOnly session cookie when you log in or sign up. It identifies your logged-in session so the platform can show your account, wallet, and history. It cannot be read by page scripts and is not used for advertising." },
      { type: "h", text: "2. No tracking or advertising cookies" },
      { type: "p", text: "We do not use third-party analytics, advertising, or cross-site tracking cookies on this platform." },
      { type: "h", text: "3. Managing cookies" },
      { type: "p", text: "Because the session cookie is required to stay logged in, blocking or clearing it will log you out. You can clear it at any time through your browser settings." },
    ],
  },
  contact: {
    title: "Contact / Support",
    icon: "shield",
    blocks: [
      { type: "callout", tone: "info", text: "This is a demo product without a live support team. The channels below describe how support is represented in the interface." },
      { type: "h", text: "1. In-app support" },
      { type: "p", text: "The \"Customer Service\" entry on the Sign Up screen and similar entries elsewhere in the app are placeholders that demonstrate where a real live-chat or ticketing integration would go." },
      { type: "h", text: "2. Reporting an issue" },
      { type: "p", text: "If you notice a bug — such as an incorrect balance, a broken flow, or unexpected behavior — the most useful thing you can do in a product like this is note what happened right before it occurred and report it to whoever is maintaining the project." },
      { type: "h", text: "3. Legal / policy questions" },
      { type: "p", text: "Questions about the Terms, Privacy Policy, or any other policy page can be directed the same way, through project maintainers rather than a live support desk." },
    ],
  },
};

export function getLegalSlugs() {
  return Object.keys(LEGAL_PAGES);
}
